[api]
server = "192.168.1.6"
port = 5000
max-age = 5400

[credentials]
username = "frag"
password = "1234"

[settings]
tokenfile = "./token.dat"

[storage]
url = "http://localhost:9000"
access_key = "frag"
secret_access_key = ""
